apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare
resources:
  - ../../base/cloudflare
  - image-automation.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: cloudflare-tunnel-token-staging
    target:
      kind: ExternalSecret
      name: cloudflare-tunnel-token
