apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 24h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    digest: sha256:d4cf08429228711cb9fe64d119befa7b54849e0c035313f6c377f1b2d6caa296
