apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
  - httproute.yaml
configMapGenerator:
  - name: qbittorrent-grafana-dashboards
    files:
      - dashboards/dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: qbittorrent
        kustomize.toolkit.fluxcd.io/substitute: disabled
