- op: replace
  path: /spec/listeners/0/hostname
  value: "*.staging.mdch-lab.dev"
- op: replace
  path: /spec/listeners/1/hostname
  value: "staging.mdch-lab.dev"
- op: replace
  path: /spec/gatewayClassName
  value: gke-l7-regional-external-managed
- op: replace
  path: /spec/addresses/0
  value: 
    type: NamedAddress
    value: cilium-gateway-mdch-lab
