- op: replace
  path: /spec/listeners/0/hostname
  value: "*.staging.mdch-lab.dev"
- op: replace
  path: /spec/listeners/1/hostname
  value: "staging.mdch-lab.dev"
- op: remove
  path: /spec/addresses
