- op: replace
  path: /spec/listeners/0/hostname
  value: "*.staging.mdch-lab.dev"
- op: replace
  path: /spec/listeners/1/hostname
  value: "staging.mdch-lab.dev"
- op: replace
  path: /spec/addresses/0/value
  value: 34.0.70.94
