apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qbittorrent
resources:
  - ../../base/qbittorrent
configMapGenerator:
  - name: qbittorrent-values
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: qbittorrent
configurations:
  - kustomizeconfig.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/ref
        value: 
          semver: '*'
    target:
      kind: OCIRepository
      name: qbittorrent
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: qbittorrent.staging.mdch-lab.dev
    target:
      kind: HTTPRoute
      name: qbittorrent-httproute
