apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - cloudflare-tunnel-token.yaml
  - cloudflare-policy.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: cloudflare-grafana-dashboards
    files:
      - dashboards/17457_rev6.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: cloudflare
        kustomize.toolkit.fluxcd.io/substitute: disabled
