static:
  configMapContent:
    conf: |-
      appConfig:
        theme: nord-frost
        customColors:
          material-dark-original:
            primary: '#f36558'
            background: '#39434C'
            background-darker: '#eb615c'
            material-light: '#f36558'
            item-text-color: '#ff948a'
            curve-factor: 5px
        enableErrorReporting: true
        layout: auto
        iconSize: medium
        language: en
      pageInfo:
        title: mdch-lab.dev
        description: Noam's Ultimate homelab
        navLinks:
          - title: GitHub
            path: https://github.com/noambenm
            target: newtab
          - title: LinkedIn
            path: https://www.linkedin.com/in/noam-ben-mordechai/
            target: newtab
        footerText: mdch-lab.dev by Noam Ben Mordechai
      sections:
        - name: Networking
          icon: fas fa-network-wired
          items:
            - &ref_0
              title: Pi-Hole
              description: DNS ad-blocking
              icon: hl-pihole
              url: https://pihole.mdch-lab.dev
              id: 0_1064_pihole
            - &ref_1
              title: Hubble
              description: Networking and Security Observability Platform
              icon: hl-cilium
              url: https://hubble.mdch-lab.dev
              id: 1_1064_hubble
          filteredItems:
            - *ref_0
            - *ref_1
        - name: Monitoring & Logging
          icon: fas fa-monitor-heart-rate
          items:
            - &ref_2
              title: Grafana
              description: Data visualised on dashboards
              icon: hl-grafana
              url: https://grafana.mdch-lab.dev
              id: 0_1875_grafana
            - &ref_3
              title: Prometheus
              description: System Statistics Aggregation with PromQL
              icon: hl-prometheus
              url: https://prometheus.mdch-lab.dev
              id: 1_1875_prometheus
            - &ref_4
              title: AlertManager
              icon: hl-alertmanager
              url: https://alertmanager.mdch-lab.dev
              id: 2_1875_alertmanager
            - &ref_5
              title: Alloy
              icon: hl-alloy
              url: https://alloy.mdch-lab.dev/
              id: 3_1875_alloy
          filteredItems:
            - *ref_2
            - *ref_3
            - *ref_4
            - *ref_5
          displayData:
            sortBy: default
            rows: 1
            cols: 1
            collapsed: false
            hideForGuests: false
        - name: Media & Entertainment
          icon: fas fa-photo-video
          displayData:
            sortBy: default
            rows: 1
            cols: 1
            collapsed: false
            hideForGuests: false
          items:
            - &ref_6
              title: Plex
              icon: hl-plex
              url: https://plex.mdch-lab.dev
              id: 0_1956_plex
            - &ref_7
              title: qBittorrent
              icon: hl-qbittorrent
              url: https://qbittorrent.mdch-lab.dev
              id: 1_1956_qbittorrent
            - &ref_8
              title: Monkeytype
              icon: si-monkeytype
              url: https://monkeytype.mdch-lab.dev
              id: 2_1956_monkeytype
          filteredItems:
            - *ref_6
            - *ref_7
            - *ref_8
        - name: Storage
          icon: fas fa-database
          displayData:
            sortBy: default
            rows: 1
            cols: 1
            collapsed: false
            hideForGuests: false
          items:
            - &ref_9
              title: Longhorn
              icon: hl-longhorn
              url: https://longhorn.mdch-lab.dev
              id: 0_725_longhorn
          filteredItems:
            - *ref_9
        - name: Apps
          icon: fas fa-photo-video
          displayData:
            sortBy: default
            rows: 1
            cols: 1
            collapsed: false
            hideForGuests: false
          items:
            - &ref_10
              title: podinfo
              icon: si-flux
              url: https://podinfo.mdch-lab.dev
              id: 0_404_podinfo
            - &ref_11
              title: SmartShopper
              icon: mdi-cart
              url: https://smartshopper.mdch-lab.dev
              id: 1_404_smartshopper
            - &ref_12
              title: SmartShopper-app
              icon: mdi-cart
              url: https://smartshopper-app.mdch-lab.dev
              id: 2_404_smartshopperapp
          filteredItems:
            - *ref_10
            - *ref_11
            - *ref_12
