apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/controllers
patches:
  - path: cilium-values.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: cilium
