---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: google-pubsub
  namespace: flux-system
spec:
  type: googlepubsub
  address: noambesandbox
  channel: flux-alerts
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pubsub-alerts
  namespace: flux-system
spec:
  providerRef:
    name: google-pubsub
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: OCIRepository 
      name: '*'
    - kind: Bucket
      name: '*'
    - kind: ImageRepository
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
  exclusionList:
    - "^Dependencies.*"
    - ".*Health check passed.*"
    - ".*stored artifact for commit.*"
