apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-slack-webhook-url.yaml
  - clusterissuer.yaml
  - coredns-custom.yaml
  - flagger-slack-webhook-url.yaml
  - flux-podmonitor.yaml
  - flux-pubsub.yaml
  - flux-webhook-receiver.yaml
  - fluxcd-slack.yaml
  - gateway.yaml
  - gcp-clustersecretstore.yaml
  - gcr-token.yaml
  - httproutes.yaml
