apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - ../../base/plex
configMapGenerator:
  - name: plex-values
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: plex
configurations:
  - kustomizeconfig.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/chart/spec/version
        value: 1.x
    target:
      kind: HelmRelease
      name: plex
