apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcpsm-sa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@noambesandbox.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      projectID: noambesandbox
      auth:
        workloadIdentityFederation:
          audience: //iam.googleapis.com/projects/320535199479/locations/global/workloadIdentityPools/mdch-lab-cluster-pool/providers/external-secrets
          serviceAccountRef:
            name: gcpsm-sa
            namespace: external-secrets
