apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wif-verification
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm
    kind: ClusterSecretStore
  target:
    name: k8s-wif-verification-secret
  data:
  - secretKey: result
    remoteRef:
      key: wif-test-secret
