apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: slack-alerts
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventMetadata:
    env: production
    cluster: mdch-lab
    kind: Raspberry Pi
    region: Beer Sheva
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: HelmRepository
      name: '*'
    - kind: OCIRepository 
      name: '*'
    - kind: Bucket
      name: '*'
    - kind: ImageRepository
      name: '*'
    - kind: ImagePolicy
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
    - kind: FluxInstance
      name: flux
  exclusionList:
    - "^Dependencies.*"
