apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/controllers
patches:
  - path: cilium-values.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: cilium
  - patch: |
      - op: replace
        path: /spec/ref
        value: 
          semver: 1.x
    target:
      kind: OCIRepository
      name: cert-manager
      namespace: cert-manager
  - patch: |
      - op: replace
        path: /spec/ref
        value:
          semver: 1.x
    target:
      kind: OCIRepository
      name: flagger
      namespace: flagger-system
  - patch: |
      - op: replace
        path: /spec/ref
        value:
          semver: '*'
    target:
      kind: OCIRepository
      name: kube-prometheus-stack
      namespace: monitoring
  - patch: |
      - op: replace
        path: /spec/ref
        value:
          semver: 1.x
    target:
      kind: OCIRepository
      name: cilium
      namespace: cilium
  - patch: |
      - op: replace
        path: /spec/chart/spec/version
        value: 1.x
    target:
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
  - patch: |
      - op: replace
        path: /spec/chart/spec/version
        value: 2.x
    target:
      kind: HelmRelease
      name: keda
      namespace: keda
