apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flagger-slack-webhook-url
  namespace: flagger-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcpsm
    kind: ClusterSecretStore
  target:
    name: flagger-slack-webhook-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: url
    remoteRef:
      key: flagger-slack-webhook-url
