name: plex-promotion
on:
  repository_dispatch:
    types:
      - HelmRelease/plex.plex

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    # Start promotion when the staging cluster has successfully
    # upgraded the Helm release to a new chart version.
    if: |
      github.event.client_payload.metadata.env == 'staging' &&
      github.event.client_payload.severity == 'info'
    steps:
      - name: Inspect Payload
        run: echo '${{ toJSON(github.event) }}'
      # Checkout main branch.
      - uses: actions/checkout@v6
        with:
          ref: main
      # Parse the event metadata to determine the chart version deployed on staging.
      - name: Get chart version from staging
        id: staging
        run: |
          VERSION=$(echo ${{ github.event.client_payload.metadata.revision }} | cut -d '@' -f1)
          echo VERSION=${VERSION} >> $GITHUB_OUTPUT
      # Patch the chart version in the production Helm release manifest.
      - name: Set chart version in production
        id: production
        env:
          CHART_VERSION: ${{ steps.staging.outputs.version }}
        run: |
          echo "set chart version to ${CHART_VERSION}"
          yq eval '(select(.kind == "HelmRelease") | .spec.chart.spec.version) = env(CHART_VERSION)' -i ./apps/base/plex/release.yaml
      # Open a Pull Request if an upgrade is needed in production.
      - name: Open promotion PR
        uses: peter-evans/create-pull-request@v8
        with:
          branch: plex-promotion
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update plex to v${{ steps.staging.outputs.version }}
          title: Promote plex release to v${{ steps.staging.outputs.version }}
          body: |
            Promote plex release on production to v${{ steps.staging.outputs.version }}

            ### ðŸ”— Release Notes
            [Release Notes](https://github.com/plexinc/pms-docker/releases/tag/helm-chart-${{ steps.staging.outputs.version }})
